// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9r4jKPKkiQ4UaXUOGhQKmc1xT8mLdQw',
    appId: '1:343772602122:android:8f8ab93a7df8d281f6a4f3',
    messagingSenderId: '343772602122',
    projectId: 'flutter-course-1af5f',
    storageBucket: 'flutter-course-1af5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1uKG0RhLmgZJpLe5q-70y-RUB8r2DNJs',
    appId: '1:343772602122:ios:a04d065b33a36e53f6a4f3',
    messagingSenderId: '343772602122',
    projectId: 'flutter-course-1af5f',
    storageBucket: 'flutter-course-1af5f.appspot.com',
    androidClientId: '343772602122-v8fckoqv12of7hp1tu4lqj9hk5fjn4jp.apps.googleusercontent.com',
    iosClientId: '343772602122-ojt916outl3g8fbu346alchg41ta3t3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourse',
  );

}